### ISSUE TITLE
Question regarding video encoding formats samples

### ISSUE THREAD

**Issue by mgogoulos** [escaped/django-video-encoding#7]
Hi, this is very nice and useful project! I tried config.py's video formats and was curious what scenarios they are optimized for. On a 60MB mp4 file,the mp4 high version produced was more than 200MB and I found that strange

Cheers

**Comment by escaped** [comment]
Hey, when I created the package, I just googled for some parameters, which seem reasonable to me. But I don't have that much experience regarding video compression. In this particular case, I suspect that the source resolution is lower than the target resolution. In this case, `django-video-encoding` will just upscale the video, which of course results in a bigger video file. This is already known, but I had not the time to fix that (https://github.com/escaped/django-video-encoding/blob/master/video_encoding/tasks.py#L61). I opened two tickets redarding these issues #8 and #9.

Does that explain your issue or do you think the source of your problem is somewhere else?

**Comment by mgogoulos** [comment]
Nice, will keep that in mind and try to open a PR once I get some results
Thanks
